version: '3.3'

services:

  axon-server:
    image: axoniq/axonserver
    hostname: axon-server
    restart: always
    ports:
      - '8024:8024'
      - '8124:8124'
      - '8224:8224'
    networks:
      - springbankNet

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ~/apps/mongo:/data/db
    networks:
      - springbankNet

  mysqldb:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ~/apps/mysql_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: springbankRootPsw
      MYSQL_DATABASE: bank
    networks:
      - springbankNet                        

networks:
  springbankNet: