server:
  port: 8082

axon:
  axonserver:
    servers: axon-server

spring:
  data:
    mongodb:
      host: mongo-container
      port: 27017
      database: user


security:
  oauth2:
    resource:
      jwt:
        key-value: springbankSignInKey